=== pebender/alexa-for-lg-webos-tv/src/bridge/lib/services/shs-to-lg-webos-tv/tv-manager/schemas/schemas/channel-list.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LG WebOS TV 'ssap://tv/getChannelList' Response",
  "type": "object",
  "required": [
    "returnValue",
    "valueList",
    "dataSource",
    "dataType",
    "cableAnalogSkipped",
    "scannedChannelCount",
    "deviceSourceIndex",
    "channelListCount",
    "channelLogoServerUrl",
    "ipChanInteractiveUrl",
    "channelList"
  ],
  "properties": {
    "returnValue": {
      "$id": "#root/returnValue",
      "title": "Returnvalue",
      "const": true
    },
    "valueList": {
      "$id": "#root/valueList",
      "title": "Valuelist",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "dataSource": {
      "$id": "#root/dataSource",
      "title": "Datasource",
      "type": "integer",
      "default": 0
    },
    "dataType": {
      "$id": "#root/dataType",
      "title": "Datatype",
      "type": "integer",
      "default": 0
    },
    "cableAnalogSkipped": {
      "$id": "#root/cableAnalogSkipped",
      "title": "Cableanalogskipped",
      "type": "boolean",
      "default": true
    },
    "scannedChannelCount": {
      "$id": "#root/scannedChannelCount",
      "title": "Scannedchannelcount",
      "type": "object",
      "required": [
        "terrestrialAnalogCount",
        "terrestrialDigitalCount",
        "cableAnalogCount",
        "cableDigitalCount",
        "satelliteDigitalCount"
      ],
      "properties": {
        "terrestrialAnalogCount": {
          "$id": "#root/scannedChannelCount/terrestrialAnalogCount",
          "title": "Terrestrialanalogcount",
          "type": "integer",
          "default": 0
        },
        "terrestrialDigitalCount": {
          "$id": "#root/scannedChannelCount/terrestrialDigitalCount",
          "title": "Terrestrialdigitalcount",
          "type": "integer",
          "default": 0
        },
        "cableAnalogCount": {
          "$id": "#root/scannedChannelCount/cableAnalogCount",
          "title": "Cableanalogcount",
          "type": "integer",
          "default": 0
        },
        "cableDigitalCount": {
          "$id": "#root/scannedChannelCount/cableDigitalCount",
          "title": "Cabledigitalcount",
          "type": "integer",
          "default": 0
        },
        "satelliteDigitalCount": {
          "$id": "#root/scannedChannelCount/satelliteDigitalCount",
          "title": "Satellitedigitalcount",
          "type": "integer",
          "default": 0
        }
      }
    },
    "deviceSourceIndex": {
      "$id": "#root/deviceSourceIndex",
      "title": "Devicesourceindex",
      "type": "integer",
      "default": 0
    },
    "channelListCount": {
      "$id": "#root/channelListCount",
      "title": "Channellistcount",
      "type": "integer",
      "default": 0
    },
    "channelLogoServerUrl": {
      "$id": "#root/channelLogoServerUrl",
      "title": "Channellogoserverurl",
      "anyOf": [
        { "type": "string", "format": "uri-reference" },
        { "const": "" }
      ]
    },
    "ipChanInteractiveUrl": {
      "$id": "#root/ipChanInteractiveUrl",
      "title": "Ipchaninteractiveurl",
      "anyOf": [
        { "type": "string", "format": "uri-reference" },
        { "const": "" }
      ]
    },
    "channelList": {
      "$id": "#root/channelList",
      "title": "Channellist",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/channelList/items",
        "title": "Items",
        "type": "object",
        "required": [
          "channelId",
          "programId",
          "signalChannelId",
          "chanCode",
          "channelMode",
          "channelModeId",
          "channelType",
          "channelTypeId",
          "channelNumber",
          "majorNumber",
          "minorNumber",
          "channelName",
          "skipped",
          "locked",
          "descrambled",
          "scrambled",
          "serviceType",
          "favoriteGroup",
          "imgUrl",
          "display",
          "satelliteName",
          "fineTuned",
          "Frequency",
          "shortCut",
          "Bandwidth",
          "HDTV",
          "Invisible",
          "TV",
          "DTV",
          "ATV",
          "Data",
          "Radio",
          "Numeric",
          "PrimaryCh",
          "specialService",
          "CASystemIDList",
          "CASystemIDListCount",
          "groupIdList",
          "channelGenreCode",
          "favoriteIdxA",
          "favoriteIdxB",
          "favoriteIdxC",
          "favoriteIdxD",
          "imgUrl2",
          "channelLogoSize",
          "ipChanServerUrl",
          "payChan",
          "IPChannelCode",
          "ipCallNumber",
          "otuFlag",
          "favoriteIdxE",
          "favoriteIdxF",
          "favoriteIdxG",
          "favoriteIdxH",
          "satelliteLcn",
          "waterMarkUrl",
          "channelNameSortKey",
          "ipChanType",
          "adultFlag",
          "ipChanCategory",
          "ipChanInteractive",
          "callSign",
          "adFlag",
          "configured",
          "lastUpdated",
          "ipChanCpId",
          "isFreeviewPlay",
          "playerService",
          "TSID",
          "SVCID"
        ],
        "properties": {
          "channelId": {
            "$id": "#root/channelList/items/channelId",
            "title": "Channelid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "programId": {
            "$id": "#root/channelList/items/programId",
            "title": "Programid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "signalChannelId": {
            "$id": "#root/channelList/items/signalChannelId",
            "title": "Signalchannelid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "chanCode": {
            "$id": "#root/channelList/items/chanCode",
            "title": "Chancode",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "channelMode": {
            "$id": "#root/channelList/items/channelMode",
            "title": "Channelmode",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "channelModeId": {
            "$id": "#root/channelList/items/channelModeId",
            "title": "Channelmodeid",
            "type": "integer",
            "default": 0
          },
          "channelType": {
            "$id": "#root/channelList/items/channelType",
            "title": "Channeltype",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "channelTypeId": {
            "$id": "#root/channelList/items/channelTypeId",
            "title": "Channeltypeid",
            "type": "integer",
            "default": 0
          },
          "channelNumber": {
            "$id": "#root/channelList/items/channelNumber",
            "title": "Channelnumber",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "majorNumber": {
            "$id": "#root/channelList/items/majorNumber",
            "title": "Majornumber",
            "type": "integer",
            "default": 0
          },
          "minorNumber": {
            "$id": "#root/channelList/items/minorNumber",
            "title": "Minornumber",
            "type": "integer",
            "default": 0
          },
          "channelName": {
            "$id": "#root/channelList/items/channelName",
            "title": "Channelname",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "skipped": {
            "$id": "#root/channelList/items/skipped",
            "title": "Skipped",
            "type": "boolean",
            "default": true
          },
          "locked": {
            "$id": "#root/channelList/items/locked",
            "title": "Locked",
            "type": "boolean",
            "default": true
          },
          "descrambled": {
            "$id": "#root/channelList/items/descrambled",
            "title": "Descrambled",
            "type": "boolean",
            "default": true
          },
          "scrambled": {
            "$id": "#root/channelList/items/scrambled",
            "title": "Scrambled",
            "type": "boolean",
            "default": true
          },
          "serviceType": {
            "$id": "#root/channelList/items/serviceType",
            "title": "Servicetype",
            "type": "integer",
            "default": 0
          },
          "favoriteGroup": {
            "$id": "#root/channelList/items/favoriteGroup",
            "title": "Favoritegroup",
            "type": "array",
            "default": []
          },
          "imgUrl": {
            "$id": "#root/channelList/items/imgUrl",
            "title": "Imgurl",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "display": {
            "$id": "#root/channelList/items/display",
            "title": "Display",
            "type": "integer",
            "default": 0
          },
          "satelliteName": {
            "$id": "#root/channelList/items/satelliteName",
            "title": "Satellitename",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "fineTuned": {
            "$id": "#root/channelList/items/fineTuned",
            "title": "Finetuned",
            "type": "boolean",
            "default": true
          },
          "Frequency": {
            "$id": "#root/channelList/items/Frequency",
            "title": "Frequency",
            "type": "integer",
            "default": 0
          },
          "shortCut": {
            "$id": "#root/channelList/items/shortCut",
            "title": "Shortcut",
            "type": "integer",
            "default": 0
          },
          "Bandwidth": {
            "$id": "#root/channelList/items/Bandwidth",
            "title": "Bandwidth",
            "type": "integer",
            "default": 0
          },
          "HDTV": {
            "$id": "#root/channelList/items/HDTV",
            "title": "Hdtv",
            "type": "boolean",
            "default": true
          },
          "Invisible": {
            "$id": "#root/channelList/items/Invisible",
            "title": "Invisible",
            "type": "boolean",
            "default": true
          },
          "TV": {
            "$id": "#root/channelList/items/TV",
            "title": "Tv",
            "type": "boolean",
            "default": true
          },
          "DTV": {
            "$id": "#root/channelList/items/DTV",
            "title": "Dtv",
            "type": "boolean",
            "default": true
          },
          "ATV": {
            "$id": "#root/channelList/items/ATV",
            "title": "Atv",
            "type": "boolean",
            "default": true
          },
          "Data": {
            "$id": "#root/channelList/items/Data",
            "title": "Data",
            "type": "boolean",
            "default": true
          },
          "Radio": {
            "$id": "#root/channelList/items/Radio",
            "title": "Radio",
            "type": "boolean",
            "default": true
          },
          "Numeric": {
            "$id": "#root/channelList/items/Numeric",
            "title": "Numeric",
            "type": "boolean",
            "default": true
          },
          "PrimaryCh": {
            "$id": "#root/channelList/items/PrimaryCh",
            "title": "Primarych",
            "type": "boolean",
            "default": true
          },
          "specialService": {
            "$id": "#root/channelList/items/specialService",
            "title": "Specialservice",
            "type": "boolean",
            "default": true
          },
          "CASystemIDList": {
            "$id": "#root/channelList/items/CASystemIDList",
            "title": "Casystemidlist",
            "type": "object",
            "required": [],
            "properties": {}
          },
          "CASystemIDListCount": {
            "$id": "#root/channelList/items/CASystemIDListCount",
            "title": "Casystemidlistcount",
            "type": "integer",
            "default": 0
          },
          "groupIdList": {
            "$id": "#root/channelList/items/groupIdList",
            "title": "Groupidlist",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/channelList/items/groupIdList/items",
              "title": "Items",
              "type": "integer",
              "default": 0
            }
          },
          "channelGenreCode": {
            "$id": "#root/channelList/items/channelGenreCode",
            "title": "Channelgenrecode",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "favoriteIdxA": {
            "$id": "#root/channelList/items/favoriteIdxA",
            "title": "Favoriteidxa",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxB": {
            "$id": "#root/channelList/items/favoriteIdxB",
            "title": "Favoriteidxb",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxC": {
            "$id": "#root/channelList/items/favoriteIdxC",
            "title": "Favoriteidxc",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxD": {
            "$id": "#root/channelList/items/favoriteIdxD",
            "title": "Favoriteidxd",
            "type": "integer",
            "default": 0
          },
          "imgUrl2": {
            "$id": "#root/channelList/items/imgUrl2",
            "title": "Imgurl2",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "channelLogoSize": {
            "$id": "#root/channelList/items/channelLogoSize",
            "title": "Channellogosize",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "ipChanServerUrl": {
            "$id": "#root/channelList/items/ipChanServerUrl",
            "title": "Ipchanserverurl",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "payChan": {
            "$id": "#root/channelList/items/payChan",
            "title": "Paychan",
            "type": "boolean",
            "default": true
          },
          "IPChannelCode": {
            "$id": "#root/channelList/items/IPChannelCode",
            "title": "Ipchannelcode",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "ipCallNumber": {
            "$id": "#root/channelList/items/ipCallNumber",
            "title": "Ipcallnumber",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "otuFlag": {
            "$id": "#root/channelList/items/otuFlag",
            "title": "Otuflag",
            "type": "boolean",
            "default": true
          },
          "favoriteIdxE": {
            "$id": "#root/channelList/items/favoriteIdxE",
            "title": "Favoriteidxe",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxF": {
            "$id": "#root/channelList/items/favoriteIdxF",
            "title": "Favoriteidxf",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxG": {
            "$id": "#root/channelList/items/favoriteIdxG",
            "title": "Favoriteidxg",
            "type": "integer",
            "default": 0
          },
          "favoriteIdxH": {
            "$id": "#root/channelList/items/favoriteIdxH",
            "title": "Favoriteidxh",
            "type": "integer",
            "default": 0
          },
          "satelliteLcn": {
            "$id": "#root/channelList/items/satelliteLcn",
            "title": "Satellitelcn",
            "type": "boolean",
            "default": true
          },
          "waterMarkUrl": {
            "$id": "#root/channelList/items/waterMarkUrl",
            "title": "Watermarkurl",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "channelNameSortKey": {
            "$id": "#root/channelList/items/channelNameSortKey",
            "title": "Channelnamesortkey",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "ipChanType": {
            "$id": "#root/channelList/items/ipChanType",
            "title": "Ipchantype",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "adultFlag": {
            "$id": "#root/channelList/items/adultFlag",
            "title": "Adultflag",
            "type": "integer",
            "default": 0
          },
          "ipChanCategory": {
            "$id": "#root/channelList/items/ipChanCategory",
            "title": "Ipchancategory",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "ipChanInteractive": {
            "$id": "#root/channelList/items/ipChanInteractive",
            "title": "Ipchaninteractive",
            "type": "boolean",
            "default": true
          },
          "callSign": {
            "$id": "#root/channelList/items/callSign",
            "title": "Callsign",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "adFlag": {
            "$id": "#root/channelList/items/adFlag",
            "title": "Adflag",
            "type": "integer",
            "default": 0
          },
          "configured": {
            "$id": "#root/channelList/items/configured",
            "title": "Configured",
            "type": "boolean",
            "default": true
          },
          "lastUpdated": {
            "$id": "#root/channelList/items/lastUpdated",
            "title": "Lastupdated",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "ipChanCpId": {
            "$id": "#root/channelList/items/ipChanCpId",
            "title": "Ipchancpid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "isFreeviewPlay": {
            "$id": "#root/channelList/items/isFreeviewPlay",
            "title": "Isfreeviewplay",
            "type": "integer",
            "default": 0
          },
          "playerService": {
            "$id": "#root/channelList/items/playerService",
            "title": "Playerservice",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "TSID": {
            "$id": "#root/channelList/items/TSID",
            "title": "Tsid",
            "type": "integer",
            "default": 0
          },
          "SVCID": {
            "$id": "#root/channelList/items/SVCID",
            "title": "Svcid",
            "type": "integer",
            "default": 0
          }
        }
      }
    }
  }
}

=== pebender/alexa-for-lg-webos-tv/src/bridge/lib/backend/schemas/examples/channel-list.json
{
  "returnValue": true,
  "valueList": "107888;107889;21212;73496;100093;114211;114213;113566;113568;113570;106657;118806;121400;29024;30697;49377;101904;68070;75511;107576;107577;122187;68081;115731;67983;67986;21213;45740;63214;21484;107246;107247;32781;24028;69874;50770;106580;123925;",
  "dataSource": 1,
  "dataType": 2,
  "cableAnalogSkipped": false,
  "scannedChannelCount": {
    "terrestrialAnalogCount": 0,
    "terrestrialDigitalCount": 38,
    "cableAnalogCount": 0,
    "cableDigitalCount": 0,
    "satelliteDigitalCount": 0
  },
  "deviceSourceIndex": 1,
  "channelListCount": 38,
  "channelLogoServerUrl": "http://aic-ngfts.lge.com/fts/gftsDownload.lge?biz_code=IBS&func_code=TMS_CHANNEL_IMG_US&file_path=/ibs/tms/channel_img_us",
  "ipChanInteractiveUrl": "",
  "channelList": [
    {
      "channelId": "1_33_3_1_0_0_0",
      "programId": "1_33_3_1_0_0_0",
      "signalChannelId": "1_33_3_1_0_0_0",
      "chanCode": "107888",
      "channelMode": "Terrestrial",
      "channelModeId": 0,
      "channelType": "Terrestrial Digital TV",
      "channelTypeId": 1,
      "channelNumber": "3-1",
      "majorNumber": 3,
      "minorNumber": 1,
      "channelName": "XHCTTI",
      "skipped": false,
      "locked": false,
      "descrambled": true,
      "scrambled": false,
      "serviceType": 2,
      "favoriteGroup": [],
      "imgUrl": "",
      "display": 1,
      "satelliteName": " ",
      "fineTuned": false,
      "Frequency": 0,
      "shortCut": 0,
      "Bandwidth": 0,
      "HDTV": false,
      "Invisible": false,
      "TV": true,
      "DTV": true,
      "ATV": false,
      "Data": false,
      "Radio": false,
      "Numeric": false,
      "PrimaryCh": true,
      "specialService": false,
      "CASystemIDList": {},
      "CASystemIDListCount": 0,
      "groupIdList": [0],
      "channelGenreCode": "61",
      "favoriteIdxA": 250,
      "favoriteIdxB": 250,
      "favoriteIdxC": 250,
      "favoriteIdxD": 250,
      "imgUrl2": "",
      "channelLogoSize": "",
      "ipChanServerUrl": "",
      "payChan": false,
      "IPChannelCode": "",
      "ipCallNumber": "",
      "otuFlag": false,
      "favoriteIdxE": 250,
      "favoriteIdxF": 250,
      "favoriteIdxG": 250,
      "favoriteIdxH": 250,
      "satelliteLcn": false,
      "waterMarkUrl": "",
      "channelNameSortKey": "",
      "ipChanType": "",
      "adultFlag": 0,
      "ipChanCategory": "",
      "ipChanInteractive": false,
      "callSign": "UNKNOWN",
      "adFlag": 0,
      "configured": false,
      "lastUpdated": "",
      "ipChanCpId": "",
      "isFreeviewPlay": 1,
      "playerService": "com.webos.service.tv",
      "TSID": 0,
      "SVCID": 0
    },
    {
      "channelId": "1_33_3_4_0_0_0",
      "programId": "1_33_3_4_0_0_0",
      "signalChannelId": "1_33_3_4_0_0_0",
      "chanCode": "107889",
      "channelMode": "Terrestrial",
      "channelModeId": 0,
      "channelType": "Terrestrial Digital TV",
      "channelTypeId": 1,
      "channelNumber": "3-4",
      "majorNumber": 3,
      "minorNumber": 4,
      "channelName": "XHCTTI",
      "skipped": false,
      "locked": false,
      "descrambled": true,
      "scrambled": false,
      "serviceType": 2,
      "favoriteGroup": [],
      "imgUrl": "",
      "display": 1,
      "satelliteName": " ",
      "fineTuned": false,
      "Frequency": 0,
      "shortCut": 0,
      "Bandwidth": 0,
      "HDTV": false,
      "Invisible": false,
      "TV": true,
      "DTV": true,
      "ATV": false,
      "Data": false,
      "Radio": false,
      "Numeric": false,
      "PrimaryCh": true,
      "specialService": false,
      "CASystemIDList": {},
      "CASystemIDListCount": 0,
      "groupIdList": [0],
      "channelGenreCode": "61",
      "favoriteIdxA": 250,
      "favoriteIdxB": 250,
      "favoriteIdxC": 250,
      "favoriteIdxD": 250,
      "imgUrl2": "",
      "channelLogoSize": "",
      "ipChanServerUrl": "",
      "payChan": false,
      "IPChannelCode": "",
      "ipCallNumber": "",
      "otuFlag": false,
      "favoriteIdxE": 250,
      "favoriteIdxF": 250,
      "favoriteIdxG": 250,
      "favoriteIdxH": 250,
      "satelliteLcn": false,
      "waterMarkUrl": "",
      "channelNameSortKey": "",
      "ipChanType": "",
      "adultFlag": 0,
      "ipChanCategory": "",
      "ipChanInteractive": false,
      "callSign": "UNKNOWN",
      "adFlag": 0,
      "configured": false,
      "lastUpdated": "",
      "ipChanCpId": "",
      "isFreeviewPlay": 1,
      "playerService": "com.webos.service.tv",
      "TSID": 0,
      "SVCID": 0
    },
    {
      "channelId": "1_8_8_1_0_0_0",
      "programId": "1_8_8_1_0_0_0",
      "signalChannelId": "1_8_8_1_0_0_0",
      "chanCode": "21212",
      "channelMode": "Terrestrial",
      "channelModeId": 0,
      "channelType": "Terrestrial Digital TV",
      "channelTypeId": 1,
      "channelNumber": "8-1",
      "majorNumber": 8,
      "minorNumber": 1,
      "channelName": "KFMB-HD",
      "skipped": false,
      "locked": false,
      "descrambled": true,
      "scrambled": false,
      "serviceType": 2,
      "favoriteGroup": [],
      "imgUrl": "",
      "display": 1,
      "satelliteName": " ",
      "fineTuned": false,
      "Frequency": 0,
      "shortCut": 0,
      "Bandwidth": 0,
      "HDTV": false,
      "Invisible": false,
      "TV": true,
      "DTV": true,
      "ATV": false,
      "Data": false,
      "Radio": false,
      "Numeric": false,
      "PrimaryCh": true,
      "specialService": false,
      "CASystemIDList": {},
      "CASystemIDListCount": 0,
      "groupIdList": [0],
      "channelGenreCode": "59",
      "favoriteIdxA": 250,
      "favoriteIdxB": 250,
      "favoriteIdxC": 250,
      "favoriteIdxD": 250,
      "imgUrl2": "",
      "channelLogoSize": "",
      "ipChanServerUrl": "",
      "payChan": false,
      "IPChannelCode": "",
      "ipCallNumber": "",
      "otuFlag": false,
      "favoriteIdxE": 250,
      "favoriteIdxF": 250,
      "favoriteIdxG": 250,
      "favoriteIdxH": 250,
      "satelliteLcn": false,
      "waterMarkUrl": "",
      "channelNameSortKey": "",
      "ipChanType": "",
      "adultFlag": 0,
      "ipChanCategory": "",
      "ipChanInteractive": false,
      "callSign": "UNKNOWN",
      "adFlag": 0,
      "configured": false,
      "lastUpdated": "",
      "ipChanCpId": "",
      "isFreeviewPlay": 1,
      "playerService": "com.webos.service.tv",
      "TSID": 0,
      "SVCID": 0
    },
    {
      "channelId": "1_8_8_2_0_0_0",
      "programId": "1_8_8_2_0_0_0",
      "signalChannelId": "1_8_8_2_0_0_0",
      "chanCode": "73496",
      "channelMode": "Terrestrial",
      "channelModeId": 0,
      "channelType": "Terrestrial Digital TV",
      "channelTypeId": 1,
      "channelNumber": "8-2",
      "majorNumber": 8,
      "minorNumber": 2,
      "channelName": "KFMB-CW",
      "skipped": false,
      "locked": false,
      "descrambled": true,
      "scrambled": false,
      "serviceType": 2,
      "favoriteGroup": [],
      "imgUrl": "/mnt/lg/cmn_data/channel_logo/minor_logo_img/73496_202003020000_h180x135.png",
      "display": 1,
      "satelliteName": " ",
      "fineTuned": false,
      "Frequency": 0,
      "shortCut": 0,
      "Bandwidth": 0,
      "HDTV": false,
      "Invisible": false,
      "TV": true,
      "DTV": true,
      "ATV": false,
      "Data": false,
      "Radio": false,
      "Numeric": false,
      "PrimaryCh": true,
      "specialService": false,
      "CASystemIDList": {},
      "CASystemIDListCount": 0,
      "groupIdList": [0],
      "channelGenreCode": "2",
      "favoriteIdxA": 250,
      "favoriteIdxB": 250,
      "favoriteIdxC": 250,
      "favoriteIdxD": 250,
      "imgUrl2": "",
      "channelLogoSize": "H180x135",
      "ipChanServerUrl": "",
      "payChan": false,
      "IPChannelCode": "",
      "ipCallNumber": "",
      "otuFlag": false,
      "favoriteIdxE": 250,
      "favoriteIdxF": 250,
      "favoriteIdxG": 250,
      "favoriteIdxH": 250,
      "satelliteLcn": false,
      "waterMarkUrl": "",
      "channelNameSortKey": "",
      "ipChanType": "",
      "adultFlag": 0,
      "ipChanCategory": "",
      "ipChanInteractive": false,
      "callSign": "UNKNOWN",
      "adFlag": 0,
      "configured": false,
      "lastUpdated": "",
      "ipChanCpId": "",
      "isFreeviewPlay": 1,
      "playerService": "com.webos.service.tv",
      "TSID": 0,
      "SVCID": 0
    },
    {
      "channelId": "1_8_8_3_0_0_0",
      "programId": "1_8_8_3_0_0_0",
      "signalChannelId": "1_8_8_3_0_0_0",
      "chanCode": "100093",
      "channelMode": "Terrestrial",
      "channelModeId": 0,
      "channelType": "Terrestrial Digital TV",
      "channelTypeId": 1,
      "channelNumber": "8-3",
      "majorNumber": 8,
      "minorNumber": 3,
      "channelName": "Laff",
      "skipped": false,
      "locked": false,
      "descrambled": true,
      "scrambled": false,
      "serviceType": 2,
      "favoriteGroup": [],
      "imgUrl": "",
      "display": 1,
      "satelliteName": " ",
      "fineTuned": false,
      "Frequency": 0,
      "shortCut": 0,
      "Bandwidth": 0,
      "HDTV": false,
      "Invisible": false,
      "TV": true,
      "DTV": true,
      "ATV": false,
      "Data": false,
      "Radio": false,
      "Numeric": false,
      "PrimaryCh": true,
      "specialService": false,
      "CASystemIDList": {},
      "CASystemIDListCount": 0,
      "groupIdList": [0],
      "channelGenreCode": "2",
      "favoriteIdxA": 250,
      "favoriteIdxB": 250,
      "favoriteIdxC": 250,
      "favoriteIdxD": 250,
      "imgUrl2": "",
      "channelLogoSize": "",
      "ipChanServerUrl": "",
      "payChan": false,
      "IPChannelCode": "",
      "ipCallNumber": "",
      "otuFlag": false,
      "favoriteIdxE": 250,
      "favoriteIdxF": 250,
      "favoriteIdxG": 250,
      "favoriteIdxH": 250,
      "satelliteLcn": false,
      "waterMarkUrl": "",
      "channelNameSortKey": "",
      "ipChanType": "",
      "adultFlag": 0,
      "ipChanCategory": "",
