=== pebender/alexa-for-lg-webos-tv/src/bridge/lib/services/shs-to-lg-webos-tv/tv-manager/schemas/schemas/launch-point-list.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LG WebOS TV 'ssap://com.webos.applicationManager/listLaunchPoints' Response",
  "type": "object",
  "required": ["returnValue", "subscribed", "caseDetail", "launchPoints"],
  "properties": {
    "returnValue": {
      "$id": "#root/returnValue",
      "title": "Returnvalue",
      "const": true
    },
    "subscribed": {
      "$id": "#root/subscribed",
      "title": "Subscribed",
      "type": "boolean",
      "default": true
    },
    "caseDetail": {
      "$id": "#root/caseDetail",
      "title": "Casedetail",
      "type": "object",
      "required": ["change"],
      "properties": {
        "change": {
          "$id": "#root/caseDetail/change",
          "title": "Change",
          "type": "array",
          "default": [],
          "items": {
            "$id": "#root/caseDetail/change/items",
            "title": "Items",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }
    },
    "launchPoints": {
      "$id": "#root/launchPoints",
      "title": "Launchpoints",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/launchPoints/items",
        "title": "Items",
        "type": "object",
        "required": [
          "systemApp",
          "removable",
          "relaunch",
          "largeIcon",
          "bgImages",
          "userData",
          "id",
          "title",
          "bgColor",
          "iconColor",
          "appDescription",
          "lptype",
          "params",
          "bgImage",
          "unmovable",
          "icon",
          "launchPointId",
          "favicon",
          "imageForRecents",
          "tileSize"
        ],
        "properties": {
          "systemApp": {
            "$id": "#root/launchPoints/items/systemApp",
            "title": "Systemapp",
            "type": "boolean",
            "default": true
          },
          "removable": {
            "$id": "#root/launchPoints/items/removable",
            "title": "Removable",
            "type": "boolean",
            "default": true
          },
          "relaunch": {
            "$id": "#root/launchPoints/items/relaunch",
            "title": "Relaunch",
            "type": "boolean",
            "default": true
          },
          "largeIcon": {
            "$id": "#root/launchPoints/items/largeIcon",
            "title": "Largeicon",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "bgImages": {
            "$id": "#root/launchPoints/items/bgImages",
            "title": "Bgimages",
            "type": "array",
            "items": {
              "type": "string",
              "format": "uri-reference"
            },
            "default": []
          },
          "userData": {
            "$id": "#root/launchPoints/items/userData",
            "title": "Userdata",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "id": {
            "$id": "#root/launchPoints/items/id",
            "title": "Id",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "title": {
            "$id": "#root/launchPoints/items/title",
            "title": "Title",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "bgColor": {
            "$id": "#root/launchPoints/items/bgColor",
            "title": "Bgcolor",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "iconColor": {
            "$id": "#root/launchPoints/items/iconColor",
            "title": "Iconcolor",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "appDescription": {
            "$id": "#root/launchPoints/items/appDescription",
            "title": "Appdescription",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "lptype": {
            "$id": "#root/launchPoints/items/lptype",
            "title": "Lptype",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "params": {
            "$id": "#root/launchPoints/items/params",
            "title": "Params",
            "type": "object",
            "required": [],
            "properties": {}
          },
          "bgImage": {
            "$id": "#root/launchPoints/items/bgImage",
            "title": "Bgimage",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "unmovable": {
            "$id": "#root/launchPoints/items/unmovable",
            "title": "Unmovable",
            "type": "boolean",
            "default": true
          },
          "icon": {
            "$id": "#root/launchPoints/items/icon",
            "title": "Icon",
            "anyOf": [
              { "type": "string", "format": "uri-reference" },
              { "const": "" }
            ]
          },
          "launchPointId": {
            "$id": "#root/launchPoints/items/launchPointId",
            "title": "Launchpointid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "favicon": {
            "$id": "#root/launchPoints/items/favicon",
            "title": "Favicon",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "imageForRecents": {
            "$id": "#root/launchPoints/items/imageForRecents",
            "title": "Imageforrecents",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "tileSize": {
            "$id": "#root/launchPoints/items/tileSize",
            "title": "Tilesize",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          }
        }
      }
    }
  }
}

=== pebender/alexa-for-lg-webos-tv/src/bridge/lib/services/shs-to-lg-webos-tv/tv-manager/schemas/examples/launch-point-list.json
{
  "returnValue": true,
  "subscribed": false,
  "caseDetail": {
    "change": ["NEWLIST_FROM_SDP"]
  },
  "launchPoints": [
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/7a258b64899caf539c866db9d1884c02748fa6f7/icon_antenna.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.livetv",
      "title": "Live TV",
      "bgColor": "",
      "iconColor": "#a3c125",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/usr/palm/applications/com.webos.app.livetv/assets/livetv.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/7a258b64899caf539c866db9d1884c02748fa6f7/icon_antenna.png",
      "launchPointId": "com.webos.app.livetv_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/6872dad0277145df466ddca0fcd22270f10c0df3/lgstore_130x130.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.discovery",
      "title": "LG Content Store",
      "bgColor": "#470a21",
      "iconColor": "#d7156d",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/mnt/otncabi/usr/palm/applications/com.webos.app.discovery/asset/hd1080/lgstore_preview.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/af874ad323754b8e628bfc66b7b3dfa570bd4c78/lgstore.png",
      "launchPointId": "com.webos.app.discovery_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/52cd139ffb4647817c2710b95c109df26a23e411/icon_universalsearch.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.voice",
      "title": "Search",
      "bgColor": "red",
      "iconColor": "#ff7449",
      "appDescription": "Search for all",
      "lptype": "default",
      "params": {
        "activateType": "home",
        "launchMode": "vkb"
      },
      "bgImage": "",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/52cd139ffb4647817c2710b95c109df26a23e411/icon_universalsearch.png",
      "launchPointId": "com.webos.app.voice_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.browser",
      "title": "Web Browser",
      "bgColor": "",
      "iconColor": "#009999",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/a995e7db4ba84ec19dbd26b196d7bf8f77841b2d/webbrowser_icon.png",
      "launchPointId": "com.webos.app.browser_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/67e9294aa5fd043b9cb347a205803f3311c1a099/icon_userguide.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.tvuserguide",
      "title": "User Guide",
      "bgColor": "#ffffff",
      "iconColor": "#ff8a00",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/67e9294aa5fd043b9cb347a205803f3311c1a099/icon_userguide.png",
      "launchPointId": "com.webos.app.tvuserguide_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/6d63c199432bddffe1e8b4d916c08ad7f7ad3deb/icon.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.connectionwizard",
      "title": "Device Connector",
      "bgColor": "",
      "iconColor": "#2c94c4",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/usr/palm/applications/com.webos.app.connectionwizard/assets/hd1080/deviceconnector_preview.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/6d63c199432bddffe1e8b4d916c08ad7f7ad3deb/icon.png",
      "launchPointId": "com.webos.app.connectionwizard_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/25da4c9c0770973314ff6b021aec70d4290fc927/icon_tvguide.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.tvguide",
      "title": "Guide",
      "bgColor": "",
      "iconColor": "#1ec15f",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/usr/palm/applications/com.webos.app.tvguide/assets/sys-assets/hd1080/tvguide_splash.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/25da4c9c0770973314ff6b021aec70d4290fc927/icon_tvguide.png",
      "launchPointId": "com.webos.app.tvguide_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/2b4695877f64da0bea6034d8ee5793bd35276f0d/icon.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.music",
      "title": "Music",
      "bgColor": "",
      "iconColor": "#9d44e1",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/usr/palm/applications/com.webos.app.music/assets/hd1080/music_splash.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/0c8eca23ef6abb9c41d834cf784a817ff0af3751/icon.png",
      "launchPointId": "com.webos.app.music_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": true,
      "removable": false,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/adf896bf0c6d2291db7e38f6603cee0e8875cbb1/icon.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.photovideo",
      "title": "Photo & Video",
      "bgColor": "",
      "iconColor": "#7c20d5",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/usr/palm/applications/com.webos.app.photovideo/assets/hd1080/photovideo_splash.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/404bc6dfa2cfde0b4df90d0ea93a099a9848a372/icon.png",
      "launchPointId": "com.webos.app.photovideo_default",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": false,
      "removable": true,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/c316bfc7a98902c96cdf437aa5cfae165074cd54/aiv_white_130x130.png",
      "bgImages": [],
      "userData": "",
      "id": "amazon",
      "title": "Amazon Prime Video",
      "bgColor": "",
      "iconColor": "#00a8e1",
      "appDescription": "",
      "lptype": "default",
      "params": {},
      "bgImage": "/media/cryptofs/apps/usr/palm/applications/amazon/amazon_preview.png",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/d6406bd5e1ae3c6232aa9b022d7f1c3e916c823f/aiv_white_80x80.png",
      "launchPointId": "amazon_default",
      "favicon": "",
      "imageForRecents": "/media/cryptofs/apps/usr/palm/applications/amazon/RECENTS.png",
      "tileSize": "normal"
    },
    {
      "systemApp": false,
      "removable": true,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/788bdc15827399f8623f7578ad8a2002121a66a9/HDMI_3.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.hdmi3",
      "title": "HDMI3",
      "bgColor": "",
      "iconColor": "#4b4b4b",
      "appDescription": "",
      "lptype": "bookmark",
      "params": {
        "deviceId": "HDMI_3"
      },
      "bgImage": "/usr/palm/applications/com.webos.app.hdmi3/assets/HDMI-3.pvr",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/6651fb2d628e9ccab62bbee522669da0d04f5d82/HDMI_3.png",
      "launchPointId": "673343",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": false,
      "removable": true,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/160c1c85512c947e996cd1b6dcbfb21796ac29c8/HDMI_2.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.hdmi2",
      "title": "HDMI2",
      "bgColor": "",
      "iconColor": "#4b4b4b",
      "appDescription": "",
      "lptype": "bookmark",
      "params": {
        "deviceId": "HDMI_2"
      },
      "bgImage": "/usr/palm/applications/com.webos.app.hdmi2/assets/HDMI-2.pvr",
      "unmovable": false,
      "icon": "http://192.168.1.12:3000/resources/e7857c704fbc9d8997df68aacf40e7ff6a2e1513/HDMI_2.png",
      "launchPointId": "419095",
      "favicon": "",
      "imageForRecents": "",
      "tileSize": "normal"
    },
    {
      "systemApp": false,
      "removable": true,
      "relaunch": false,
      "largeIcon": "http://192.168.1.12:3000/resources/fc2a8790b37459687d3b2ae71e0e6a3261fd4a21/settopbox.png",
      "bgImages": [],
      "userData": "",
      "id": "com.webos.app.hdmi1",
      "title": "Roku",
      "bgColor": "",
      "iconColor": "#4b4b4b",
      "appDescription": "",
